baseURL = "https://blog.read-me.fun"
languageCode = "en-us"
title = "晔 晔"
theme = "cactus"
copyright = "詹" # cactus will use title if copyright is not set
disqusShortname = "example" # Used when comments is enabled. Cactus will use site title if not set
# googleAnalytics = "UA-1234-5"

[markup.goldmark.renderer]
unsafe= true

# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4

    
[params]
  css = ["css/custom.css"]
  mathjax = true  # not required

  colortheme = "white" # dark, light, white, or classic
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  showAllPostsArchive = false # default
  

  # Home page settings
  description = "Hi, 欢迎来到我的博客"
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false
  postsOnHomePage = 5
  tagsOverview = true
  showProjectsList = true
  projectsUrl = "https://github.com/zhanyeye"

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02"

  # Post page settings
  show_updated = false

  [params.comments]
    enabled = true
    engine = "giscus"
    [params.comments.giscus]  
      repo = "zhanyeye/zhanyeye.github.io"
      repoid = "MDEwOlJlcG9zaXRvcnkxNzk4MDk2NzY="
      category = "Comments"
      categoryid = "DIC_kwDOCretjM4CndZR"
      label = "comment"


  [[params.social]]
    name = "github"
    link = "https://github.com/zhanyeye"
  
  [[params.social]]
    name = "email"
    link = "zhanyeye@qq.com"  # no need for "mailto:" at the start
