name: Sync Discussions to Blog  

on:
  workflow_dispatch:     # 手动触发  
  discussion:  
    types: [created, edited, deleted]  

jobs:  
  sync-discussions:  
    runs-on: ubuntu-latest  

    steps:  
    # Step 1: 检出仓库代码  
    - name: Checkout repository  
      uses: actions/checkout@v3  

    # Step 2: 运行 discussions-to-blog Action  
    - name: Sync Discussions to Markdown  
      uses: zhanyeye/discussions-to-blog-action@composite-action
      with:   
        categories: "Announcements, General"
        output_dir: "content/posts"
        branch: main
        commit_message: "Sync Discussions to Markdown"
